version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - deepface
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recognition
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  deepface:
    build:
      context: ./deepface
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - deepface_weights:/app/deepface/.deepface/weights      
    networks:
      - app-network

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
    volumes:
      - .:/app  
    depends_on:
      -db
      -web
    networks:
      - app-network      

networks:
  app-network:

volumes:
  postgres_data:
  deepface_weights: